name: st_water
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - affine=2.3.1=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - blosc=1.21.1=h83bc5f7_3
  - boost-cpp=1.78.0=h75c5d50_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_0
  - cfitsio=4.1.0=hd9d235c_0
  - click=8.1.3=py39hf3d152e_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cpuonly=2.0=0
  - cudatoolkit=11.6.0=hecad31d_10
  - cudnn=8.4.1.50=hed8a83a_0
  - curl=7.85.0=h2283fc2_0
  - expat=2.4.9=h27087fc_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=hc2a2eb6_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_0
  - freexl=1.0.6=h166bdaf_1
  - future=0.18.2=py39hf3d152e_5
  - geos=3.11.0=h27087fc_0
  - geotiff=1.7.1=h4fc65e6_3
  - gettext=0.19.8.1=h27087fc_1009
  - giflib=5.2.1=h36c2ea0_2
  - hdf4=4.2.15=h9772cbc_4
  - hdf5=1.12.2=nompi_h4df4325_100
  - icu=70.1=h27087fc_0
  - jpeg=9e=h166bdaf_2
  - json-c=0.16=hc379101_0
  - kealib=1.4.15=ha7026e8_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h08a2579_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcurl=7.85.0=h2283fc2_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgdal=3.5.2=h84f2e82_1
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.74.0=h7a41b64_0
  - libiconv=1.17=h166bdaf_0
  - libkml=1.3.0=h37653c0_1015
  - liblapack=3.9.0=16_linux64_mkl
  - libnetcdf=4.8.1=nompi_h21705cb_104
  - libnghttp2=1.47.0=hff17c54_1
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.38=h753d276_0
  - libpq=14.5=he2d8382_0
  - libprotobuf=3.19.4=h780b84a_0
  - librttopo=1.1.0=hf730bdb_11
  - libspatialite=5.0.1=hd36657c_19
  - libsqlite=3.39.4=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h55922b4_4
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.2=h4c7fe37_1
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.12=h166bdaf_4
  - llvm-openmp=14.0.4=he0ac6c6_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - magma=2.5.4=h6103c52_2
  - mkl=2022.1.0=h84fe81f_915
  - nccl=2.14.3.1=h0800d71_0
  - ncurses=6.3=h27087fc_1
  - ninja=1.11.0=h924138e_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.23.3=py39hba7629e_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.0.5=h166bdaf_2
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=hc3806b6_1
  - pillow=9.2.0=py39hd5dbb17_2
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - poppler=22.04.0=h0733791_3
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.5=ha7cec9f_0
  - proj=9.0.1=h93bde94_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.9.13=h2660328_0_cpython
  - python_abi=3.9=2_cp39
  - pytorch=1.10.2=cuda112py39h4de5995_1
  - pytorch-gpu=1.10.2=cuda112py39h0bbbad9_1
  - pytorch-mutex=1.0=cpu
  - rasterio=1.3.2=py39h082961e_0
  - readline=8.1.2=h0f457ee_0
  - setuptools=59.5.0=py39hf3d152e_0
  - sleef=3.5.1=h9b69904_2
  - snappy=1.1.9=hbd366e4_1
  - snuggs=1.4.7=py_0
  - sqlite=3.39.4=h4ff8645_0
  - tbb=2021.6.0=h924138e_0
  - tiledb=2.11.3=h3f4058f_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.10.2=py39_cpu
  - torchvision=0.10.1=py39cuda112hc5182df_0_cuda
  - typing_extensions=4.4.0=pyha770c72_0
  - tzcode=2022d=h166bdaf_0
  - tzdata=2022d=h191b570_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xerces-c=3.2.3=h55805fa_5
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.12=h166bdaf_4
  - zstd=1.5.2=h6239696_4
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.2
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.49.1
    - hydra-core==1.2.0
    - idna==3.4
    - imagecodecs==2022.9.26
    - importlib-metadata==5.0.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - multidict==6.0.2
    - oauthlib==3.2.1
    - omegaconf==2.2.3
    - opencv-python==4.6.0.66
    - packaging==21.3
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pytorch-lightning==1.7.7
    - pyyaml==6.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - six==1.16.0
    - st-water-seg==0.0.1
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tifffile==2022.8.12
    - toml==0.10.2
    - torchmetrics==0.10.0
    - tqdm==4.64.1
    - urllib3==1.26.12
    - werkzeug==2.2.2
    - yapf==0.32.0
    - yarl==1.8.1
    - zipp==3.9.0
prefix: /home/mpurri/miniconda3/envs/st_water
